### PR TITLE
Add config entry point loader

### PR DESCRIPTION
**Pull request by roborourke**
Explicitly checks for and load the custom config entry point.

### CODE REVIEW

**Comment by joehoyle** [comment]
I don't think this should be in the wp-config, it should be implemented in `core` after all the modules bootstrap has completed.

**Comment by roborourke** [comment]
Hm, this felt like a more natural fit but I'll make a PR on Core now.

**Comment by rmccue** [comment]
cms has a wp-config file where this might fit?

**Comment by roborourke** [comment]
@rmccue it moved here

**Comment by rmccue** [comment]
Oh I was actually thinking of https://github.com/humanmade/local-server/blob/master/wp-config.php but that's local-server

**Pull request closed without merging**
