### PR TITLE
Upgrade WordPress to 5.2

### PR DESCRIPTION
**Pull request by joehoyle**

### CODE REVIEW

**Comment by rmccue** [comment]
Shouldn't this be a dependency of `cms` instead anyway? 🤔

**Comment by joehoyle** [comment]
It probably _could_ but probably makes more sense to go along with the cms-installer?

**Review by roborourke — APPROVED** [review]
Agree with @joehoyle here. It doesn't make a huge difference ultimately but semantically due to this composer plugin's follow up actions the WP installer should be a dep of this package.

**Comment by rmccue** [comment]
> It doesn't make a huge difference ultimately but semantically due to this composer plugin's follow up actions the WP installer should be a dep of this package.

IMO, this package should be focussed on just the installer part of it, rather than declaring a dependency on actual packages. None of this package actually depends on the WP package at all, so makes sense to have that controlled in `cms` instead.

Also, one less package to release :D

**Comment by roborourke** [comment]
That is true. Alrighty then :)

**Comment by roborourke** [comment]
Created #8 and https://github.com/humanmade/platform-cms/pull/54 to supercede this one.

**Pull request closed without merging**
